#!/bin/make

PATH_1024 = ../code/data/DNN/neuron1024_Conversion
PATH_4096 = ../code/data/DNN/neuron4096_Conversion
PATH_16384 = ../code/data/DNN/neuron16384_Conversion
PATH_65536 = ../code/data/DNN/neuron65536_Conversion

all:
	mkdir $(PATH_1024)
	mkdir $(PATH_4096)
	mkdir $(PATH_16384)
	mkdir $(PATH_65536)

clean:
